name: discordcli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  crypt: ^4.3.0
  dotenv: ^4.1.0
  postgres: ^2.6.1
  redis: ^3.1.0
  sembast: ^3.4.9
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
